# ]==================================================================================================================================[
#   _____                      .__    ___________.__       .__    .__
#  /     \   _________________ |  |__ \_   _____/|__| _____|  |__ |__| ____    ____
# /  \ /  \ /  _ \_  __ \____ \|  |  \ |    __)  |  |/  ___/  |  \|  |/    \  / ___\
#/    Y    (  <_> )  | \/  |_> >   Y  \|     \   |  |\___ \|   Y  \  |   |  \/ /_/  >
#\____|__  /\____/|__|  |   __/|___|  /\___  /   |__/____  >___|  /__|___|  /\___  /
#        \/             |__|        \/     \/            \/     \/        \//_____/
# ]==================================================================================================================================[
#
# Plugin Version: 1.0.0
# Author Discord Name: morphie
# Support Discord: http://discord.com/invite/6bnU9xn
# Contributors: gmancash14, itsliambeans
#
# ]==================================================================================================================================[
Settings:
  # Enable or disable the plugin credits item in the /mf menu.
  PluginCredits:
    Enabled: false
  # Enable or disable the plugins update checker. (Admins and Console messages for new plugin updates.)
  UpdateChecker: true
  # Enable or disable if every custom fish caught should contain "Caught by PLAYER on DATE"
  FishCaughtBy: true
  # Set this to your preferred weight metric. EX: "lbs"
  FishWeightMetric: none
  # Set this to your preferred currency symbol.
  CurrencySymbol: "$"

# ]==================================================================================================================================[
# Storage method, can be MySQL, Redis, or SQLite (Default)
StorageMethod: "SQLite"

# Requires 'StorageMethod' to be SQLite
SQLite:
  TablePrefix: 'mf_'

# Requires 'StorageMethod' to be MySQL
MySQL:
  Username: "root"
  Password: "password"
  Host: "localhost"
  Port: 3306
  SSL: false
  Database: "minecraft"
  TablePrefix: "mf_"

# Requires 'StorageMethod' to be Redis
Redis:
  Hostname: "localhost"
  Port: 11111
  Password: "password"
  SSL: false
  KeyPrefix: "mf_"

# ]==================================================================================================================================[
# Fish Sell Prices

CommonFishPrice: 100
RareFishPrice: 250
EpicFishPrice: 500
LegendaryFishPrice: 750
MythicFishPrice: 1000

# ]==================================================================================================================================[
# Fish Tier Catch Chance
# These are %'s out of 100. Default example is there is an 50% chance to catch a custom fish, 35% chance it would be a common fish.

ChanceToCatchCustomFish: 50
CommonFishChance: 75
RareFishChance: 45
EpicFishChance: 25
LegendaryFishChance: 10
MythicFishChance: 5

# ]==================================================================================================================================[